// Generated by https://quicktype.io

export interface Palabra {
  _id:        string;
  title:      string;
  definition: string;
  status:     Status;
}

export enum Status {
  NotPublished = "NOT_PUBLISHED",
  Published = "PUBLISHED",
}
